name: "Build page by mkwebsite"
description: "Build page using the `mkwebsite` tool."
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: sudo apt install liblua5.4-dev -y
      shell: bash
    - name: Install mkwebsite
      run: cargo install mkwebsite --version 0.4.0
      shell: bash
    - name: Build page
      run: mkwebsite
      shell: bash
