[package]
name = "mkwebsite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
katex = "0.4.6"
logos = "0.13.0"
