[package]
name = "mkwebsite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
katex = { version = "0.4.6", default-features = false, features = ["duktape"] }
logos = "0.13.0"
