[package]
name = "mkwebsite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
emojis = "0.6.1"
fs_extra = "1.3.0"
lazy_static = "1.4.0"
logos = "0.13.0"
mathjax = { version = "0.1.1", default-features = false, features = ["node"] }
rayon = "1.7.0"
rust-ini = "0.19.0"
walkdir = "2.3.3"
