pre-release-replacements = [
    { file="action.yaml", search="--version .*", replace="--version {{version}}" },

    { file="CHANGELOG.md", search="# Unreleased", replace="# {{version}}" },
    { file="CHANGELOG.md", search="<!-- updated by cargo-release -->", replace="<!-- updated by cargo-release -->\n\n# Unreleased" },
]
pre-release-hook = ["git", "tag", "v{{version}}"]
